[package]
name = "orml-auction"
version = "0.0.1"
authors = ["Acala Developers"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sr-primitives = { git = "https://github.com/paritytech/substrate.git", default-features = false }
runtime_io = { package = "sr-io", git = "https://github.com/paritytech/substrate.git", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate.git", default-features = false }

palette-support = { git = "https://github.com/paritytech/substrate.git", default-features = false }
palette-system = { git = "https://github.com/paritytech/substrate.git", default-features = false }

orml-traits = { path = "../traits", default-features = false }
orml-utilities = { path = "../utilities", default-features = false }

[dev-dependencies]
primitives = { package = "substrate-primitives",  git = "https://github.com/paritytech/substrate.git" }
substrate-runtime-interface = { git = "https://github.com/paritytech/substrate.git", features = ['disable_target_static_assertions'] }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sr-primitives/std",
	"runtime_io/std",
	"rstd/std",
	"palette-support/std",
	"palette-system/std",
	"orml-traits/std",
	"orml-utilities/std",
]
